// JOAF Bangla Search Utility v2.0
// English টাইপ করলে বাংলা match করবে + continent mapping
(function() {

// Continent → countries mapping (for community group search)
const CONTINENT_MAP = {
  // JOAF Asia — Asia র সব দেশ (Bangladesh বাদে)
  'joaf asia': ['afghanistan','armenia','azerbaijan','bahrain','bhutan','brunei','cambodia','china','cyprus','georgia','india','indonesia','iran','iraq','israel','japan','jordan','kazakhstan','kuwait','kyrgyzstan','laos','lebanon','malaysia','maldives','mongolia','myanmar','nepal','north korea','oman','pakistan','palestine','philippines','qatar','saudi','saudi arabia','singapore','south korea','sri lanka','syria','taiwan','tajikistan','thailand','timor','turkey','turkmenistan','uae','united arab emirates','uzbekistan','vietnam','yemen'],
  // JOAF Middle East
  'joaf middle east': ['bahrain','egypt','iran','iraq','israel','jordan','kuwait','lebanon','oman','palestine','qatar','saudi','saudi arabia','syria','turkey','uae','united arab emirates','yemen'],
  // JOAF Europe
  'joaf europe': ['albania','andorra','austria','belarus','belgium','bosnia','bulgaria','croatia','cyprus','czech','denmark','estonia','finland','france','germany','greece','hungary','iceland','ireland','italy','kosovo','latvia','liechtenstein','lithuania','luxembourg','malta','moldova','monaco','montenegro','netherlands','north macedonia','norway','poland','portugal','romania','russia','san marino','serbia','slovakia','slovenia','spain','sweden','switzerland','ukraine','uk','united kingdom','england','scotland','wales','vatican'],
  // JOAF Australia (we have this group)
  'joaf australia': ['australia','new zealand','fiji','papua','solomon','vanuatu','samoa','tonga','kiribati','micronesia','palau','nauru','tuvalu'],
  // JOAF Canada
  'joaf canada': ['canada'],
  // JOAF USA
  'joaf usa': ['usa','united states','america'],
};

// Bangladesh districts (English → Bengali)
const DISTRICTS = {
  'dhaka':'ঢাকা','chittagong':'চট্টগ্রাম','chattogram':'চট্টগ্রাম',
  'sylhet':'সিলেট','rajshahi':'রাজশাহী','khulna':'খুলনা',
  'barisal':'বরিশাল','barishal':'বরিশাল','rangpur':'রংপুর',
  'mymensingh':'ময়মনসিংহ','comilla':'কুমিল্লা','cumilla':'কুমিল্লা',
  'narayanganj':'নারায়ণগঞ্জ','gazipur':'গাজীপুর','tangail':'টাঙ্গাইল',
  'faridpur':'ফরিদপুর','jessore':'যশোর','jashore':'যশোর',
  'noakhali':'নোয়াখালী','bogra':'বগুড়া','bogura':'বগুড়া',
  'dinajpur':'দিনাজপুর','pabna':'পাবনা','narsingdi':'নরসিংদী',
  'manikganj':'মানিকগঞ্জ','munshiganj':'মুন্সীগঞ্জ',
  'shariatpur':'শরীয়তপুর','madaripur':'মাদারীপুর',
  'gopalganj':'গোপালগঞ্জ','kishoreganj':'কিশোরগঞ্জ',
  'netrokona':'নেত্রকোনা','jamalpur':'জামালপুর','sherpur':'শেরপুর',
  'brahmanbaria':'ব্রাহ্মণবাড়িয়া','chandpur':'চাঁদপুর',
  'feni':'ফেনী','lakshmipur':'লক্ষ্মীপুর','coxsbazar':'কক্সবাজার',
  'bandarban':'বান্দরবান','rangamati':'রাঙ্গামাটি',
  'khagrachhari':'খাগড়াছড়ি','habiganj':'হবিগঞ্জ',
  'moulvibazar':'মৌলভীবাজার','sunamganj':'সুনামগঞ্জ',
  'naogaon':'নওগাঁ','chapainawabganj':'চাঁপাইনবাবগঞ্জ',
  'natore':'নাটোর','sirajganj':'সিরাজগঞ্জ','joypurhat':'জয়পুরহাট',
  'satkhira':'সাতক্ষীরা','jhenaidah':'ঝিনাইদহ','magura':'মাগুরা',
  'narail':'নড়াইল','bagerhat':'বাগেরহাট','meherpur':'মেহেরপুর',
  'chuadanga':'চুয়াডাঙ্গা','kushtia':'কুষ্টিয়া','jhalokati':'ঝালকাঠি',
  'patuakhali':'পটুয়াখালী','pirojpur':'পিরোজপুর','bhola':'ভোলা',
  'barguna':'বরগুনা','lalmonirhat':'লালমনিরহাট','nilphamari':'নীলফামারী',
  'gaibandha':'গাইবান্ধা','kurigram':'কুড়িগ্রাম','panchagarh':'পঞ্চগড়',
  'thakurgaon':'ঠাকুরগাঁও',
};

// International cities/countries
const INTL = {
  'australia':'অস্ট্রেলিয়া','aus':'অস্ট্রেলিয়া',
  'usa':'যুক্তরাষ্ট্র','us':'যুক্তরাষ্ট্র','america':'যুক্তরাষ্ট্র',
  'uk':'যুক্তরাজ্য','england':'যুক্তরাজ্য','britain':'যুক্তরাজ্য',
  'canada':'কানাডা','europe':'ইউরোপ','germany':'জার্মানি',
  'berlin':'বার্লিন','london':'লন্ডন','new york':'নিউ ইয়র্ক',
  'newyork':'নিউ ইয়র্ক','toronto':'টরন্টো','sydney':'সিডনি',
  'malaysia':'মালয়েশিয়া','singapore':'সিঙ্গাপুর','dubai':'দুবাই',
  'saudi':'সৌদি','saudi arabia':'সৌদি আরব','riyadh':'রিয়াদ',
  'qatar':'কাতার','kuwait':'কুয়েত','bahrain':'বাহরাইন',
  'oman':'ওমান','uae':'সংযুক্ত আরব আমিরাত','abu dhabi':'আবুধাবি',
  'italy':'ইতালি','france':'ফ্রান্স','spain':'স্পেন',
  'japan':'জাপান','korea':'কোরিয়া','china':'চীন',
  'india':'ভারত','pakistan':'পাকিস্তান','nepal':'নেপাল',
  'sri lanka':'শ্রীলঙ্কা','myanmar':'মিয়ানমার','thailand':'থাইল্যান্ড',
  'indonesia':'ইন্দোনেশিয়া','philippines':'ফিলিপাইন',
  'middle east':'মধ্যপ্রাচ্য','middleeast':'মধ্যপ্রাচ্য',
  'asia':'এশিয়া','africa':'আফ্রিকা','europe':'ইউরোপ',
  'ireland':'আয়ারল্যান্ড','netherlands':'নেদারল্যান্ড',
  'sweden':'সুইডেন','norway':'নরওয়ে','denmark':'ডেনমার্ক',
  'finland':'ফিনল্যান্ড','switzerland':'সুইজারল্যান্ড',
  'austria':'অস্ট্রিয়া','belgium':'বেলজিয়াম','portugal':'পর্তুগাল',
  'greece':'গ্রিস','poland':'পোল্যান্ড','russia':'রাশিয়া',
  'turkey':'তুরস্ক','iran':'ইরান','iraq':'ইরাক',
  'jordan':'জর্ডান','lebanon':'লেবানন','syria':'সিরিয়া',
  'israel':'ইসরায়েল','egypt':'মিশর','libya':'লিবিয়া',
  'tunisia':'তিউনিসিয়া','morocco':'মরক্কো','algeria':'আলজেরিয়া',
  'nigeria':'নাইজেরিয়া','ghana':'ঘানা','kenya':'কেনিয়া',
  'ethiopia':'ইথিওপিয়া','south africa':'দক্ষিণ আফ্রিকা',
  'new zealand':'নিউজিল্যান্ড','fiji':'ফিজি',
  'bangladesh':'বাংলাদেশ',
};

const UPAZILAS = {
  'abhaynagor':'অভয়নগর',
  'adabar':'আদাবর',
  'adamdighi':'আদমদীঘি',
  'aditmari':'আদিতমারী',
  'agailjhara':'আগৈলঝাড়া',
  'ajmiriganj':'আজমিরীগঞ্জ',
  'akhaura':'আখাউড়া',
  'akkelpur':'আক্কেলপুর',
  'alamdanga':'আলমডাঙ্গা',
  'alfadanga':'আলফাডাঙ্গা',
  'alikadam':'আলীকদম',
  'amtali':'আমতলী',
  'anwara':'আনোয়ারা',
  'araihazar':'আড়াইহাজার',
  'ashuganj':'আশুগঞ্জ',
  'ashulia':'আশুলিয়া',
  'assasuni':'আশাশুনি',
  'atgharia':'আটঘরিয়া',
  'atpara':'আটপাড়া',
  'atrai':'আত্রাই',
  'atwari':'আটোয়ারী',
  'austagram':'অষ্টগ্রাম',
  'azimpur':'আজিমপুর',
  'babuganj':'বাবুগঞ্জ',
  'badalgachhi':'বদলগাছী',
  'badarganj':'বদরগঞ্জ',
  'badda':'বাড্ডা',
  'bagaichhari':'বাঘাইছড়ি',
  'bagatipara':'বাগাতিপাড়া',
  'bagerhat sadar':'বাগেরহাট সদর',
  'bagha':'বাঘা',
  'bagherpar':'বাঘারপাড়া',
  'bahubal':'বাহুবল',
  'bajitpur':'বাজিতপুর',
  'bakerganj':'বাকেরগঞ্জ',
  'bakshiganj':'বকশীগঞ্জ',
  'balaganj':'বালাগঞ্জ',
  'baliadangi':'বালিয়াডাঙ্গী',
  'baliakandi':'বালিয়াকান্দি',
  'bamna':'বামনা',
  'banaripara':'বানারীপাড়া',
  'bancharampur':'বাঞ্ছারামপুর',
  'bandarban sadar':'বান্দরবান সদর',
  'bangshal':'বংশাল',
  'baniachong':'বানিয়াচং',
  'banshkhali':'বাঁশখালী',
  'baraigram':'বড়াইগ্রাম',
  'barguna sadar':'বরগুনা সদর',
  'barhatta':'বারহাট্টা',
  'barisal sadar':'বরিশাল সদর',
  'barkal':'বরকল',
  'barlekha':'বড়লেখা',
  'barura':'বরুড়া',
  'basail':'বাসাইল',
  'batiaghata':'বটিয়াঘাটা',
  'bauphal':'বাউফল',
  'beanibazar':'বিয়ানীবাজার',
  'begumganj':'বেগমগঞ্জ',
  'belabo':'বেলাব',
  'belkuchi':'বেলকুচি',
  'bera':'বেড়া',
  'betagi':'বেতাগী',
  'bhairab':'ভৈরব',
  'bhaluka':'ভালুকা',
  'bhandaria':'ভান্ডারিয়া',
  'bhanga':'ভাঙ্গা',
  'bhangura':'ভাঙ্গুড়া',
  'bhashantek':'ভাষানটেক',
  'bheramara':'ভেড়ামারা',
  'bhola sadar':'ভোলা সদর',
  'bholahat':'ভোলাহাট',
  'bhuapur':'ভূঞাপুর',
  'bhurungamari':'ভুরুঙ্গামারী',
  'bijnagar':'বিজয়নগর',
  'bilaichhari':'বিলাইছড়ি',
  'birampur':'বিরামপুর',
  'birol':'বিরল',
  'bishwambarpur':'বিশ্বম্ভরপুর',
  'boalkhali':'বোয়ালখালী',
  'boalmari':'বোয়ালমারী',
  'bochaganj':'বোচাগঞ্জ',
  'boda':'বোদা',
  'bogura sadar':'বগুড়া সদর',
  'brahmanbaria sadar':'ব্রাহ্মণবাড়িয়া সদর',
  'brahmanpara':'ব্রাহ্মণপাড়া',
  'burhanuddin':'বোরহানউদ্দিন',
  'burichang':'বুড়িচং',
  'chakaria':'চকরিয়া',
  'chandanaish':'চন্দনাইশ',
  'chandina':'চান্দিনা',
  'chandpur sadar':'চাঁদপুর সদর',
  'chapainawabganj sadar':'চাঁপাইনবাবগঞ্জ সদর',
  'char rajibpur':'চর রাজিবপুর',
  'charfasson':'চরফ্যাশন',
  'charghat':'চারঘাট',
  'chatkhil':'চাটখিল',
  'chatmohar':'চাটমোহর',
  'chauddagram':'চৌদ্দগ্রাম',
  'chauhali':'চৌহালী',
  'chhagalnaiya':'ছাগলনাইয়া',
  'chhatak':'ছাতক',
  'chilmari':'চিলমারী',
  'chirirbandar':'চিরিরবন্দর',
  'chitalmari':'চিতলমারী',
  'chokbazar':'চকবাজার',
  'chougachha':'চৌগাছা',
  'chuadanga sadar':'চুয়াডাঙ্গা সদর',
  'chunarughat':'চুনারুঘাট',
  'comilla sadar':'কুমিল্লা সদর',
  'companiganj':'কোম্পানীগঞ্জ',
  'coxsbazar sadar':'কক্সবাজার সদর',
  'dacope':'দাকোপ',
  'daganbhuiyan':'দাগনভূঁইয়া',
  'dakshin khan':'দক্ষিণখান',
  'dakshin surma':'দক্ষিণ সুরমা',
  'damuddya':'ডামুড্যা',
  'damurhuda':'দামুড়হুদা',
  'darus salam':'দারুস সালাম',
  'dashmina':'দশমিনা',
  'daudkandi':'দাউদকান্দি',
  'daulatkhan':'দৌলতখান',
  'daulatpur':'দৌলতপুর',
  'debhata':'দেবহাটা',
  'debidwar':'দেবিদ্বার',
  'debiganj':'দেবীগঞ্জ',
  'delduar':'দেলদুয়ার',
  'dewanganj':'দেওয়ানগঞ্জ',
  'dhamoirhat':'ধামইরহাট',
  'dhamrai':'ধামরাই',
  'dhanbari':'ধনবাড়ী',
  'dhanmondi':'ধানমন্ডি',
  'dharmapasha':'ধর্মপাশা',
  'dhobaura':'ধোবাউড়া',
  'dhunat':'ধুনট',
  'dighalia':'দিঘলিয়া',
  'dighinala':'দীঘিনালা',
  'dimla':'ডিমলা',
  'dinajpur sadar':'দিনাজপুর সদর',
  'dirai':'দিরাই',
  'dohar':'দোহার',
  'domar':'ডোমার',
  'dowarabazar':'দোয়ারাবাজার',
  'dumki':'দুমকি',
  'dumuria':'ডুমুরিয়া',
  'dupchanchia':'দুপচাঁচিয়া',
  'durgapur':'দুর্গাপুর',
  'fakirhat':'ফকিরহাট',
  'faridganj':'ফরিদগঞ্জ',
  'faridpur sadar':'ফরিদপুর সদর',
  'fatikchhari':'ফটিকছড়ি',
  'fenchuganj':'ফেঞ্চুগঞ্জ',
  'feni sadar':'ফেনী সদর',
  'fulbari dinajpur':'ফুলবাড়ী',
  'fulbaria':'ফুলবাড়িয়া',
  'fulchhari':'ফুলছড়ি',
  'fulgazi':'ফুলগাজী',
  'fulpur':'ফুলপুর',
  'gabtali':'গাবতলী',
  'gaffargaon':'গফরগাঁও',
  'gaibandha sadar':'গাইবান্ধা সদর',
  'galachipa':'গলাচিপা',
  'gangachara':'গঙ্গাচড়া',
  'gangni':'গাংনী',
  'gaurnadi':'গৌরনদী',
  'gazaria':'গজারিয়া',
  'gazipur sadar':'গাজীপুর সদর',
  'gendaria':'গেন্ডারিয়া',
  'ghatail':'ঘাটাইল',
  'ghior':'ঘিওর',
  'ghoraghat':'ঘোড়াঘাট',
  'goalanda':'গোয়ালন্দ',
  'gobindaganj':'গোবিন্দগঞ্জ',
  'godagari':'গোদাগাড়ী',
  'golapganj':'গোলাপগঞ্জ',
  'gomastapur':'গোমস্তাপুর',
  'gopalganj sadar':'গোপালগঞ্জ সদর',
  'gopalpur':'গোপালপুর',
  'gosairhat':'গোসাইরহাট',
  'gouripur':'গৌরীপুর',
  'gowainghat':'গোয়াইনঘাট',
  'guimara':'গুইমারা',
  'gurudaspur':'গুরুদাসপুর',
  'habiganj sadar':'হবিগঞ্জ সদর',
  'haimchar':'হাইমচর',
  'hajiganj':'হাজীগঞ্জ',
  'hakimpur':'হাকিমপুর',
  'haluaghat':'হালুয়াঘাট',
  'harinakunda':'হরিণাকুণ্ডু',
  'haripur':'হরিপুর',
  'harirampur':'হরিরামপুর',
  'hathazari':'হাটহাজারী',
  'hatia':'হাতিয়া',
  'hatibandha':'হাতীবান্ধা',
  'hazaribagh':'হাজারীবাগ',
  'hijla':'হিজলা',
  'homna':'হোমনা',
  'hossainpur':'হোসেনপুর',
  'ishwardi':'ঈশ্বরদী',
  'ishwarganj':'ঈশ্বরগঞ্জ',
  'islampur':'ইসলামপুর',
  'itna':'ইটনা',
  'jagannathpur':'জগন্নাথপুর',
  'jaintapur':'জৈন্তাপুর',
  'jajira':'জাজিরা',
  'jakiganj':'জকিগঞ্জ',
  'jaldhaka':'জলঢাকা',
  'jamalganj':'জামালগঞ্জ',
  'jamalpur sadar':'জামালপুর সদর',
  'jatrabari':'যাত্রাবাড়ী',
  'jessore sadar':'যশোর সদর',
  'jhalakathi sadar':'ঝালকাঠি সদর',
  'jhenaidah sadar':'ঝিনাইদহ সদর',
  'jhenaigati':'ঝিনাইগাতী',
  'jhikargachha':'ঝিকরগাছা',
  'jibannagar':'জীবননগর',
  'joypurhat sadar':'জয়পুরহাট সদর',
  'jurachhari':'জুরাছড়ি',
  'juri':'জুড়ী',
  'kabirhat':'কবিরহাট',
  'kachua':'কচুয়া',
  'kafrul':'কাফরুল',
  'kahalu':'কাহালু',
  'kaharole':'কাহারোল',
  'kalai':'কালাই',
  'kalapara':'কলাপাড়া',
  'kalia':'কালিয়া',
  'kaliakair':'কালিয়াকৈর',
  'kaliganj':'কালীগঞ্জ',
  'kalihati':'কালিহাতী',
  'kalkini':'কালকিনি',
  'kalukhali':'কালুখালী',
  'kamalganj':'কমলগঞ্জ',
  'kamalnagar':'কমলনগর',
  'kamarkhand':'কামারখন্দ',
  'kanaighat':'কানাইঘাট',
  'kapasia':'কাপাসিয়া',
  'kaptai':'কাপ্তাই',
  'karimganj':'করিমগঞ্জ',
  'kasba':'কসবা',
  'kashiani':'কাশিয়ানী',
  'kathalia':'কাঠালিয়া',
  'katiadi':'কটিয়াদী',
  'kaunia':'কাউনিয়া',
  'kawkhali':'কাউখালী',
  'kawkhali pirojpur':'কাউখালী',
  'kazipur':'কাজীপুর',
  'kendua':'কেন্দুয়া',
  'keraniganj':'কেরানীগঞ্জ',
  'keshabpur':'কেশবপুর',
  'khagrachhari sadar':'খাগড়াছড়ি সদর',
  'khaliajuri':'খালিয়াজুরী',
  'khansama':'খানসামা',
  'khetlal':'ক্ষেতলাল',
  'khilgaon':'খিলগাঁও',
  'khilkhet':'খিলক্ষেত',
  'khoksa':'খোকসা',
  'khulna sadar':'খুলনা সদর',
  'kishoreganj sadar':'কিশোরগঞ্জ সদর',
  'kolaroa':'কলারোয়া',
  'kolmakanda':'কলমাকান্দা',
  'kotalipara':'কোটালীপাড়া',
  'kotchandpur':'কোটচাঁদপুর',
  'koyra':'কয়রা',
  'kulaura':'কুলাউড়া',
  'kuliarchar':'কুলিয়ারচর',
  'kumarkhali':'কুমারখালী',
  'kurigram sadar':'কুড়িগ্রাম সদর',
  'kushtia sadar':'কুষ্টিয়া সদর',
  'kutubdia':'কুতুবদিয়া',
  'lakhai':'লাখাই',
  'laksam':'লাকসাম',
  'lakshmichhari':'লক্ষ্মীছড়ি',
  'lakshmipur sadar':'লক্ষ্মীপুর সদর',
  'lalbagh':'লালবাগ',
  'lalmohan':'লালমোহন',
  'lalmonirhat sadar':'লালমনিরহাট সদর',
  'lalpur':'লালপুর',
  'lama':'লামা',
  'langadu':'লংগদু',
  'lohagara':'লোহাগাড়া',
  'lohagora':'লোহাগড়া',
  'louhajong':'লৌহজং',
  'madan':'মদন',
  'madarganj':'মাদারগঞ্জ',
  'madaripur sadar':'মাদারীপুর সদর',
  'madhabpur':'মাধবপুর',
  'madhukali':'মধুখালী',
  'madhupur':'মধুপুর',
  'madhyanagar':'মধ্যনগর',
  'magura sadar':'মাগুরা সদর',
  'mahadebpur':'মহাদেবপুর',
  'mahalchhari':'মহালছড়ি',
  'maheshkhali':'মহেশখালী',
  'maheshpur':'মহেশপুর',
  'manda':'মান্দা',
  'manikchhari':'মানিকছড়ি',
  'manikganj sadar':'মানিকগঞ্জ সদর',
  'manirampur':'মণিরামপুর',
  'manpura':'মনপুরা',
  'mathbaria':'মঠবাড়িয়া',
  'matirangga':'মাটিরাঙ্গা',
  'matlab dakshin':'মতলব দক্ষিণ',
  'matlab uttar':'মতলব উত্তর',
  'meghna':'মেঘনা',
  'mehendiganj':'মেহেন্দিগঞ্জ',
  'meherpur sadar':'মেহেরপুর সদর',
  'melandah':'মেলান্দহ',
  'mirpur':'মিরপুর',
  'mirsharai':'মীরসরাই',
  'mirzaganj':'মির্জাগঞ্জ',
  'mirzapur':'মির্জাপুর',
  'mithamain':'মিঠামইন',
  'mithapukur':'মিঠাপুকুর',
  'mohammadpur':'মহম্মদপুর',
  'mohanganj':'মোহনগঞ্জ',
  'mohanpur':'মোহনপুর',
  'mollahat':'মোল্লাহাট',
  'mongla':'মোংলা',
  'monohardi':'মনোহরদী',
  'monoharganj':'মনোহরগঞ্জ',
  'morrelganj':'মোড়েলগঞ্জ',
  'motijheel':'মতিঝিল',
  'moulvibazar sadar':'মৌলভীবাজার সদর',
  'mujibnagar':'মুজিবনগর',
  'muksudpur':'মুকসুদপুর',
  'muktagacha':'মুক্তাগাছা',
  'muladi':'মুলাদী',
  'munshiganj sadar':'মুন্সীগঞ্জ সদর',
  'muradnagar':'মুরাদনগর',
  'mymensingh sadar':'ময়মনসিংহ সদর',
  'nabiganj':'নবীগঞ্জ',
  'nabinagar':'নবীনগর',
  'nachol':'নাচোল',
  'nagarkanda':'নগরকান্দা',
  'nagarpur':'নাগরপুর',
  'nageshwari':'নাগেশ্বরী',
  'naikhangchhari':'নাইক্ষ্যংছড়ি',
  'nakla':'নকলা',
  'nalchiti':'নলছিটি',
  'nalitabari':'নালিতাবাড়ী',
  'nandail':'নান্দাইল',
  'nandigram':'নন্দীগ্রাম',
  'nangalkot':'নাঙ্গলকোট',
  'naniarchar':'নানিয়ারচর',
  'naogaon sadar':'নওগাঁ সদর',
  'narail sadar':'নড়াইল সদর',
  'narayanganj sadar':'নারায়ণগঞ্জ সদর',
  'naria':'নড়িয়া',
  'narsingdi sadar':'নরসিংদী সদর',
  'natore sadar':'নাটোর সদর',
  'nawabganj':'নবাবগঞ্জ',
  'nazirpur':'নাজিরপুর',
  'nesarabad':'নেছারাবাদ',
  'netrokona sadar':'নেত্রকোনা সদর',
  'niamatpur':'নিয়ামতপুর',
  'nikli':'নিকলী',
  'nilphamari sadar':'নীলফামারী সদর',
  'noakhali sadar':'নোয়াখালী সদর',
  'osmaninagar':'ওসমানীনগর',
  'pabna sadar':'পাবনা সদর',
  'paikgachha':'পাইকগাছা',
  'pakundia':'পাকুন্দিয়া',
  'palash':'পলাশ',
  'palashbari':'পলাশবাড়ী',
  'pallabi':'পল্লবী',
  'paltan':'পল্টন',
  'panchagarh sadar':'পঞ্চগড় সদর',
  'panchbibi':'পাঁচবিবি',
  'panchhari':'পানছড়ি',
  'pangsha':'পাংশা',
  'parbatipur':'পার্বতীপুর',
  'parshuram':'পরশুরাম',
  'patgram':'পাটগ্রাম',
  'pathorghata':'পাথরঘাটা',
  'patiya':'পটিয়া',
  'patnitala':'পত্নীতলা',
  'patuakhali sadar':'পটুয়াখালী সদর',
  'pekua':'পেকুয়া',
  'phultala':'ফুলতলা',
  'pirgachha':'পীরগাছা',
  'pirojpur sadar':'পিরোজপুর সদর',
  'poba':'পবা',
  'porsha':'পোরশা',
  'purbadhala':'পূর্বধলা',
  'puthia':'পুঠিয়া',
  'raiganj':'রায়গঞ্জ',
  'raipur':'রায়পুর',
  'raipura':'রায়পুরা',
  'rajapur':'রাজাপুর',
  'rajarhat':'রাজারহাট',
  'rajasthali':'রাজস্থলী',
  'rajbari sadar':'রাজবাড়ী সদর',
  'rajnagar':'রাজনগর',
  'rajoir':'রাজৈর',
  'rajshahi sadar':'রাজশাহী সদর',
  'ramganj':'রামগঞ্জ',
  'ramgarh':'রামগড়',
  'ramgati':'রামগতি',
  'ramna':'রমনা',
  'rampal':'রামপাল',
  'ramu':'রামু',
  'rangabali':'রাঙ্গাবালী',
  'rangamati sadar':'রাঙ্গামাটি সদর',
  'rangpur sadar':'রংপুর সদর',
  'rangunia':'রাঙ্গুনিয়া',
  'raninagar':'রাণীনগর',
  'ranisankail':'রাণীশংকৈল',
  'raozan':'রাউজান',
  'rowangchhari':'রোয়াংছড়ি',
  'rowmari':'রৌমারী',
  'ruma':'রুমা',
  'rupganj':'রূপগঞ্জ',
  'rupsha':'রূপসা',
  'sabujbagh':'সবুজবাগ',
  'sadullapur':'সাদুল্লাপুর',
  'saghata':'সাঘাটা',
  'saidpur':'সৈয়দপুর',
  'sakhipur':'সখিপুর',
  'saltha':'সালথা',
  'sandwip':'সন্দ্বীপ',
  'santhia':'সাঁথিয়া',
  'sapahar':'সাপাহার',
  'sarail':'সরাইল',
  'sariakandi':'সারিয়াকান্দি',
  'sarishabari':'সরিষাবাড়ী',
  'satkania':'সাতকানিয়া',
  'satkhira sadar':'সাতক্ষীরা সদর',
  'saturia':'সাটুরিয়া',
  'savar':'সাভার',
  'senbag':'সেনবাগ',
  'shahbag':'শাহবাগ',
  'shahjadpur':'শাহজাদপুর',
  'shahjahanpur':'শাহজাহানপুর',
  'shahrasti':'শাহরাস্তি',
  'shailkupa':'শৈলকুপা',
  'shajahanpur':'শাজাহানপুর',
  'shalikha':'শালিখা',
  'sharankhola':'শরণখোলা',
  'shariatpur sadar':'শরীয়তপুর সদর',
  'sharsha':'শার্শা',
  'sherpur sadar':'শেরপুর সদর',
  'shibaloy':'শিবালয়',
  'shibchar':'শিবচর',
  'shibganj':'শিবগঞ্জ',
  'shibpur':'শিবপুর',
  'shyamnagar':'শ্যামনগর',
  'shyampur':'শ্যামপুর',
  'singair':'সিংগাইর',
  'singra':'সিংড়া',
  'sirajdikhan':'সিরাজদিখান',
  'sirajganj sadar':'সিরাজগঞ্জ সদর',
  'sitakunda':'সীতাকুণ্ড',
  'sonagazi':'সোনাগাজী',
  'sonaimuri':'সোনাইমুড়ী',
  'sonargaon':'সোনারগাঁও',
  'sonatala':'সোনাতলা',
  'sreemangal':'শ্রীমঙ্গল',
  'sreenagar':'শ্রীনগর',
  'sreepur':'শ্রীপুর',
  'sreepur magura':'শ্রীপুর',
  'sribardi':'শ্রীবরদী',
  'subarnachar':'সুবর্ণচর',
  'sujanagar':'সুজানগর',
  'sulla':'শাল্লা',
  'sunamganj sadar':'সুনামগঞ্জ সদর',
  'sundarganj':'সুন্দরগঞ্জ',
  'sutrapur':'সূত্রাপুর',
  'sylhet sadar':'সিলেট সদর',
  'tahirpur':'তাহিরপুর',
  'tajumuddin':'তজুমদ্দিন',
  'tala':'তালা',
  'taltali':'তালতলী',
  'tangail sadar':'টাঙ্গাইল সদর',
  'tanore':'তানোর',
  'taraganj':'তারাগঞ্জ',
  'tarail':'তাড়াইল',
  'tarakanda':'তারাকান্দা',
  'tarash':'তাড়াশ',
  'tejgaon':'তেজগাঁও',
  'teknaf':'টেকনাফ',
  'terokhada':'তেরখাদা',
  'tetulia':'তেঁতুলিয়া',
  'thakurgaon sadar':'ঠাকুরগাঁও সদর',
  'thanchi':'থানচি',
  'titas':'তিতাস',
  'tongi':'টঙ্গী',
  'tongibari':'টঙ্গীবাড়ী',
  'trishal':'ত্রিশাল',
  'tungipara':'টুঙ্গীপাড়া',
  'turag':'তুরাগ',
  'ukhia':'উখিয়া',
  'ulipur':'উলিপুর',
  'ullapara':'উল্লাপাড়া',
  'uttara':'উত্তরা',
  'uttarkhan':'উত্তরখান',
  'uzirpur':'উজিরপুর',
  'vedarganj':'ভেদরগঞ্জ',
  'zianagar':'জিয়ানগর',
};

const ALL_MAP = {...DISTRICTS, ...INTL, ...UPAZILAS};

// Check if query matches a continent group
function continentMatch(query, groupName) {
  if (!groupName) return false;
  const gName = groupName.toLowerCase();
  const q = query.toLowerCase().trim();
  
  for (const [group, countries] of Object.entries(CONTINENT_MAP)) {
    const groupKey = group.replace('joaf ','');
    // Check if this group matches the groupName
    const isMatch = gName.includes(groupKey) || gName.includes(group);
    if (!isMatch) continue;
    
    // Check if query matches any country in this group
    if (countries.some(country => {
      return country === q || 
             country.startsWith(q) || 
             q.startsWith(country) ||
             country.includes(q) ||
             q.includes(country);
    })) return true;
  }
  return false;
}

// Main search function
window.bnSearch = function(query, text, groupName) {
  if (!query || !text) return false;
  const q = query.toLowerCase().trim();
  const t = text.toLowerCase();
  const g = (groupName || text).toLowerCase();

  // Direct match (handles English text in area field)
  if (t.includes(q)) return true;

  // English query → check if text contains the English word directly
  // e.g. area="bhola bazar" and query="bhola" → match
  if (t.split(/[\s,.-]+/).some(word => word.startsWith(q) || q.startsWith(word))) return true;

  // Reverse: Bengali text matches English query via transliteration
  // e.g. query="bhola", text="ভোলা" → match via ALL_MAP
  const bn = ALL_MAP[q];
  if (bn && t.includes(bn.toLowerCase())) return true;
  
  // Also check: query is Bengali, text is English
  // e.g. query="ভোলা", check if ALL_MAP has reverse match
  for (const [en, bnWord] of Object.entries(ALL_MAP)) {
    if (bnWord.toLowerCase() === q && t.includes(en)) return true;
    // partial Bengali match e.g. "ভোলা সদর" contains "ভোলা"
    if (bnWord.toLowerCase().includes(q) && t.includes(en)) return true;
    // partial English in text e.g. text="bhola bazar" query="ভোলা"
    if (bnWord.toLowerCase() === q && t.split(/[\s,.-]+/).some(w => en.startsWith(w) || w.startsWith(en))) return true;
  }
  
  // Bengali query → search Bengali text directly (already done via t.includes)
  // Bengali query → also try each word
  const qWords = q.split(/[\s,.-]+/).filter(w => w.length >= 2);
  for (const qw of qWords) {
    if (t.includes(qw)) return true;
    const bnVal = ALL_MAP[qw];
    if (bnVal && t.includes(bnVal.toLowerCase())) return true;
  }

  // Continent match — e.g. "malaysia" → JOAF Asia
  if (groupName && continentMatch(q, groupName)) return true;

  // Additional partial transliteration

  // Partial match
  for (const [en, bnWord] of Object.entries(ALL_MAP)) {
    if (en.startsWith(q) && t.includes(bnWord.toLowerCase())) return true;
    if (q.startsWith(en) && en.length >= 3 && t.includes(bnWord.toLowerCase())) return true;
  }

  // Partial continent match
  if (groupName) {
    for (const [group, countries] of Object.entries(CONTINENT_MAP)) {
      if (g.includes(group.replace('joaf ',''))) {
        if (countries.some(c => c.startsWith(q) || q.startsWith(c.slice(0,4)))) return true;
      }
    }
  }

  return false;
};

})();
